name: Relase Binary
run-name: Relase ${{ inputs.binary_name }}/${{ inputs.version }}/${{ inputs.target_triple }}
on:
  workflow_dispatch:
    inputs:
      binary_name:
        required: true
        type: string
      version:
        required: true
        type: string
      target_triple:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Relase Binary
        run: |
          curl -o ${{ inputs.binary_name }}-${{ inputs.version }}-${{ inputs.target_triple }} https://capi-binaries.s3.amazonaws.com/${{ inputs.binary_name }}/${{ inputs.version }}/${{ inputs.target_triple }}
          gh release view ${{ inputs.binary_name }}-${{ inputs.version }} --json url > release-url.txt || true 
          [[ -s ./release-url.txt ]] || gh release create ${{ inputs.binary_name }}-${{ inputs.version }} --notes "${{ inputs.binary_name }}-${{ inputs.version }}"
          gh release upload ${{ inputs.binary_name }}-${{ inputs.version }} ${{ inputs.binary_name }}-${{ inputs.version }}-${{ inputs.target_triple }}
        env:
          GH_TOKEN: ${{ github.token }}
